#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# die "reason" stops the wizard loudly. Every use below marks a state where
# continuing would produce a co-signer that looks configured but is not.
die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

RW="${RAILWAY_BIN:-railway}"
PROJECT="${COSIGNER_PROJECT:-centient-work}"
ENVIRONMENT="${COSIGNER_ENV:-production}"
SVC=cosigner
APP="${COSIGNER_APP_SERVICE:-web}"

# rw runs the Railway CLI already scoped to this project + environment, so no
# command below can silently act on a different one.
rw() { "$RW" "$@" --project "$PROJECT" --environment "$ENVIRONMENT"; }

# set_var NAME VALUE sets a service variable without the value ever appearing in
# argv (and therefore never in the process list or a shell history file).
set_var() {
  local svc="$1" name="$2" value="$3"
  printf '%s' "$value" | rw variable set --stdin "$name" --service "$svc" --skip-deploys >/dev/null
  printf '  %s✓ set%s %s on %s\n' "$GREEN" "$RESET" "$name" "$svc"
}

banner "Centient policy co-signer — Railway setup (issue #8)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "This configures the cosigner service in the $PROJECT project."
say "You enter every secret yourself; nothing is printed back or written to disk."
if ! command -v "$RW" >/dev/null 2>&1; then
  die "railway CLI not found. Install it, or set RAILWAY_BIN to its full path."
fi
"$RW" whoami || die "Not logged in. Run: railway login"
step "Confirm the account above owns $PROJECT."
confirm "Continue?" || die "Stopped."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Read-only database role"
say "This credential is the boundary that is actually enforced. Get it right."
step "Open the Postgres service in $PROJECT and use its Data / query tab."
step "Run the CREATE ROLE + GRANT block from docs/cosigner-deployment.md."
step "Then run the SET ROLE test in that doc: the UPDATE must fail."
warn "If that UPDATE succeeds, stop — the grant is wrong and the isolation is fake."
confirm "Did the UPDATE fail with permission denied?" || die "Fix the grant first."
say ""
say "Now build the connection string. Same project, so use the INTERNAL host:"
say "  postgresql://centient_cosigner:PASSWORD@postgres.railway.internal:5432/railway"
ask_secret COSIGNER_DB_URL "Paste the full COSIGNER_DATABASE_URL:"
[[ -n "$COSIGNER_DB_URL" ]] || die "A database URL is required."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Service configuration"
say "Setting start command, health check, and an explicitly empty pre-deploy."
step "The empty pre-deploy matters: the repo-root railway.json runs"
step "prisma migrate deploy, which this read-only service must never do."
rw environment edit --service-config "$SVC" deploy.startCommand "npm run cosign"
rw environment edit --service-config "$SVC" deploy.healthcheckPath "/health"
rw environment edit --service-config "$SVC" deploy.preDeployCommand ""
rw environment edit --service-config "$SVC" deploy.restartPolicyType "ON_FAILURE"
rw environment edit --service-config "$SVC" source.repo "webnxt-2030/Centient"
rw environment edit --service-config "$SVC" source.branch "develop"
say ""
step "Watch paths, so a push only redeploys the service it actually touched."
rw environment edit --service-config "$SVC" build.watchPatterns \
  '["services/cosigner/**","lib/stellar/**","prisma/**","package.json"]'
warn "Verify these landed before continuing — the CLI can report success without persisting."
rw environment config --json | grep -A6 '"'"$SVC"'"' || true
confirm "Does the config above show the start command and watch paths?" \
  || die "Set them in the dashboard (Settings → Deploy) before continuing."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Co-signer secrets"
say "These live on the cosigner service and nowhere else."
step "The policy seed is the second signature. If the app can also see it,"
step "there is no 2-of-3 — the app refuses to start in that state."
ask_secret POLICY_SEED "Paste STELLAR_POLICY_SIGNER_SECRET (S…):"
[[ "$POLICY_SEED" == S* ]] || die "That does not look like a Stellar secret seed."
say ""
step "Shared HMAC secret. Generate one with: openssl rand -hex 32"
ask_secret SHARED_SECRET "Paste COSIGNER_SHARED_SECRET (32+ chars):"
(( ${#SHARED_SECRET} >= 32 )) || die "Shared secret must be at least 32 characters."
set_var "$SVC" STELLAR_POLICY_SIGNER_SECRET "$POLICY_SEED"
set_var "$SVC" COSIGNER_SHARED_SECRET "$SHARED_SECRET"
set_var "$SVC" COSIGNER_DATABASE_URL "$COSIGNER_DB_URL"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Co-signer policy settings"
say "The cap is configured here independently of the app's own cap on purpose:"
say "two processes, two separately configured limits, one genuine second opinion."
ask CAP_UNITS "Daily cap in units [200000000000 = 200 USDC]:"
CAP_UNITS="${CAP_UNITS:-200000000000}"
set_var "$SVC" COSIGNER_DAILY_CAP_UNITS "$CAP_UNITS"
set_var "$SVC" COSIGNER_ISOLATION_LEVEL "same-workspace"
set_var "$SVC" STELLAR_NETWORK "testnet"
set_var "$SVC" STELLAR_USDC_ISSUER "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
set_var "$SVC" STELLAR_USDC_CODE "USDC"
note "same-workspace fails closed on the public network. That is the mainnet gate."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Deploy and verify the co-signer"
rw redeploy --service "$SVC" --yes 2>/dev/null || rw up --service "$SVC" --detach || true
say "Watch the deploy until it is live:"
say "  railway logs --service $SVC"
step "You want: [cosigner] policy signer G… listening on … (isolation: same-workspace)"
warn "If it exited instead, the log names the missing variable. There are no fallbacks."
confirm "Is the co-signer listening?" || die "Fix the boot error, then re-run this wizard."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Point the app at it"
say "Same project, so the app reaches the co-signer over the private network."
say "The URL is:  http://$SVC.railway.internal:8080/cosign"
warn "The app must NOT hold STELLAR_POLICY_SIGNER_SECRET. Check now:"
rw variable list --service "$APP" --kv 2>/dev/null | cut -d= -f1 | grep -E 'POLICY_SIGNER_SECRET|ALLOW_LOCAL_COSIGNER' \
  && warn "^ delete those from $APP before continuing" \
  || say "  ✓ neither is present on $APP"
confirm "Ready to set the app's co-signer variables?" || die "Stopped."
set_var "$APP" COSIGNER_URL "http://$SVC.railway.internal:8080/cosign"
set_var "$APP" COSIGNER_SHARED_SECRET "$SHARED_SECRET"
set_var "$APP" COSIGNER_ISOLATION_LEVEL "same-workspace"
note "If $APP now crash-loops naming both variables, the policy seed is still set there."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Prove the refusals"
say "A co-signer that signs whatever it is handed adds a key, not a control."
step "From the app service shell, an unauthenticated request must be refused 401:"
say "  railway ssh --service $APP -- \\"
say "    curl -s -o /dev/null -w '%{http_code}\\n' -X POST \\"
say "    http://$SVC.railway.internal:8080/cosign -H 'content-type: application/json' -d '{}'"
step "Then run one testnet payout and confirm two distinct signatures settle."
warn "Separately: $APP has no STELLAR_PLATFORM_ACCOUNT / STELLAR_OPS_SIGNER_SECRET /"
warn "STELLAR_POLICY_SIGNER_PUBLIC, so the multisig payout path is not configured yet."
warn "Payouts will fail before reaching the co-signer until those are set."

finish
